os: linux
dist: xenial
services:
    xvfb
language: node_js
node_js:
    - node
install:
    - npm install testcafe
    - npm install testcafe-browser-provider-nightmare --save-dev
script:
    - xvfb-run testcafe nightmare tests/